#!/bin/bash

## `echo`s:
## * 'true' - if all upgrades have been installed
## * 'false' - if there are pending upgrades
## * nothing - if apt-get is currently locked
##
## optional argument "skip-refresh" can be used to not refresh metadata (useful
## when it's already up to date, like after installing updates)
##
## Forwards the exit code of the package manager.

skip_refresh=false
if [ "$1" = "skip-refresh" ]; then
    skip_refresh=true
fi

if [ -e /etc/system-release ]; then
    ## Fedora
    if command -v dnf >/dev/null; then
        yum=dnf
    else
        yum=yum
    fi
    # shellcheck disable=SC2034
    yum_output="$($yum -yq check-update)"
    exit_code="$?"
    [ "$exit_code" -eq 100 ] && echo "false" && exit 0
    [ "$exit_code" -eq 0 ] && echo "true"
elif [ -e /etc/debian_version ]; then
    ## Debian
    set -e
    set -o pipefail
    if ! $skip_refresh; then
        apt-get -q update >&2
    fi
    apt_get_upgrade_output="$(LANG="C" apt-get -s upgrade 2>&1)"
    exit_code="$?"
    # shellcheck disable=SC2266
    echo "$apt_get_upgrade_output" | awk "/^Inst/{ print $2 }" | [ "$(wc -L)" -eq 0 ] && echo "true" || echo "false"
    echo "$apt_get_upgrade_output" >&2
elif [ -e /etc/arch-release ]; then
    ## Archlinux
    checkupdates >/dev/null 2>&1
    exit_code="$?"
    [ "$exit_code" -eq 2 ] && echo "true" && exit 0
    [ "$exit_code" -eq 0 ] && echo "false"
elif [ -e /etc/gentoo-release ]; then
    ## Gentoo
    set -e
    set -o pipefail
    emerge_output="$(emerge -puDv @world 2>&1)"
    exit_code="$?"
    echo "$emerge_output" | grep -qF -- '[ebuild' && echo "false" || echo "true"
elif [ -e /etc/alpine-release ]; then
    ## Alpine and APK based distros
    set -e
    set -o pipefail
    if ! $skip_refresh; then
        sudo apk update -q >&2
    fi
    upgrades="$(apk list --upgradable)"
    exit_code="$?"
    [ -n "${upgrades}" ] && echo "false" || echo "true"
else
    echo "Check not implemented for this distribution" >&2
    exit 1
fi

exit "$exit_code"
