include:
  - project: 'QubesOS/qubes-continuous-integration'
    file: '/r4.0/gitlab-base.yml'
  - project: 'QubesOS/qubes-continuous-integration'
    file: '/r4.0/gitlab-vm.yml'

checks:tests:
  stage: checks
  before_script:
    - sudo dnf install -y python3-pip python3-gobject-base ShellCheck
    - pip3 install --quiet -r ci/requirements.txt
  script:
    - ./run-tests
    - shellcheck -e SC1117 $(grep -l '^#!/bin/\(ba\)\?sh' $(git ls-files))
  after_script:
    - "PATH=$PATH:$HOME/.local/bin"
    - codecov
