#!/bin/sh
if [ "$2" = up ]; then
	INET=$(/sbin/ip addr show dev "$1" | /bin/grep inet)
	qubesdb-write /qubes-netvm-external-ip "$INET"
fi
if [ "$2" = down ]; then
	qubesdb-write /qubes-netvm-external-ip ""
fi
