#!/bin/sh

# Source Qubes library.
# shellcheck source=init/functions
. /usr/lib/qubes/init/functions

/usr/lib/qubes/qubes-setup-dnat-to-ns

# FIXME: Tinyproxy does not reload DNS servers.
if under_systemd ; then
    systemctl --no-block try-restart qubes-updates-proxy.service
else
    service qubes-updates-proxy try-restart
fi
