#!/bin/sh

if [ -x /usr/sbin/xenstore-read ]; then
	XENSTORE_READ="/usr/sbin/xenstore-read"
else
	XENSTORE_READ="$XENSTORE_READ"
fi

ip=`$XENSTORE_READ qubes-ip 2> /dev/null`
if [ x$ip != x ]; then
    netmask=`$XENSTORE_READ qubes-netmask`
    gateway=`$XENSTORE_READ qubes-gateway`
    secondary_dns=`$XENSTORE_READ qubes-secondary-dns`
    /sbin/ifconfig $INTERFACE $ip netmask 255.255.255.255
    /sbin/ifconfig $INTERFACE up
    /sbin/route add -host $gateway dev $INTERFACE
    /sbin/route add default gw $gateway
    /sbin/ethtool -K $INTERFACE sg off
    /sbin/ethtool -K $INTERFACE tx off
    echo "nameserver $gateway" > /etc/resolv.conf
    echo "nameserver $secondary_dns" >> /etc/resolv.conf
	network=$($XENSTORE_READ qubes-netvm-network 2>/dev/null)
	if [ "x$network" != "x" ]; then
		gateway=$($XENSTORE_READ qubes-netvm-gateway)
		netmask=$($XENSTORE_READ qubes-netvm-netmask)
		secondary_dns=$($XENSTORE_READ qubes-netvm-secondary-dns)
		echo "NS1=$gateway" > /var/run/qubes/qubes-ns
		echo "NS2=$secondary_dns" >> /var/run/qubes/qubes-ns
		/usr/lib/qubes/qubes-setup-dnat-to-ns
		[ -x /rw/config/qubes-ip-change-hook ] && /rw/config/qubes-ip-change-hook
		# XXX: Backward compatibility
		[ -x /rw/config/qubes_ip_change_hook ] && /rw/config/qubes_ip_change_hook
	fi
    if [ -f /var/run/qubes-service/network-manager ]; then
        cat > /etc/sysconfig/network-scripts/ifcfg-$INTERFACE <<__EOF__
DEVICE=$INTERFACE
IPADDR=$ip
NETMASK=255.255.255.255
NETWORK=$ip
ONBOOT=yes
GATEWAYDEV=$INTERFACE
GATEWAY=$gateway
__EOF__
    fi
fi
