#!/bin/bash

# License: GPL-2+
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.



is_minimal_netvm() {
	test -f /run/qubes-service/minimal-netvm
}

is_minimal_usbvm() {
	test -f /run/qubes-service/minimal-usbvm
}


setup_minimal_netvm() {
	if [ "$UID" == "0" ]; then
		/usr/lib/systemd/systemd-sysctl /etc/sysctl.d/82-qubes-minimal-sys-net.conf.optional
	else
		/usr/bin/systemctl --user --runtime mask gvfs-daemon.service
	fi
}

is_minimal_netvm && setup_minimal_netvm
