#!/bin/sh --
#
# The Qubes OS Project, http://www.qubes-os.org
#
# Copyright (C) 2010  Rafal Wojtczuk  <rafal@invisiblethingslab.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# lack of -e is intentional
set -ux

# we use “is this variable set” a lot, and use variables that we haven’t set, so
# unset these variables first, to ensure that values from the environment don’t
# cause problems.
unset qopen_opts filename seen_dashdash i
qopen_opts='' seen_dashdash=''

usage() {
    printf 'Usage: %s [--view-only] [--] filename\n' "$0" >&2
    exit 2
}

for i; do
    if [ -z "$seen_dashdash" ]; then
        case $i in
        (--) seen_dashdash=x; continue;;
        (--view-only) qopen_opts=--view-only; continue;;
        (-*) usage;;
        esac
    fi
    if [ -z "${filename+x}" ]; then
        filename="$i"
    else
        usage
    fi
done

[ -n "${filename-}" ] || usage

expr "@$filename" : '@[A-Za-z][A-Za-z0-9+]*://'>/dev/null
case $? in
(0)
    # shellcheck disable=SC2016
    exec /usr/lib/qubes/qrexec-client-vm -- @dispvm qubes.OpenURL \
        /bin/sh -c 'printf %s\\n "$1"; exec cat >/dev/null' sh "$filename";;
(1) exec /usr/lib/qubes/qrexec-client-vm -- @dispvm qubes.OpenInVM \
    /usr/lib/qubes/qopen-in-vm $qopen_opts -- "$filename";;
(*) exit "$?";;
esac >/dev/null 2>&1 </dev/null
