#!/bin/sh
set -e
#
# The Qubes OS Project, http://www.qubes-os.org
#
# Copyright (C) 2010  Rafal Wojtczuk  <rafal@invisiblethingslab.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
#

if [ $# -lt 2 ] ; then
	
	if [ "${0##*/}" = "qvm-move-to-vm" ] || [ "${0##*/}" = "qvm-copy-to-vm" ]; then
		echo "usage: $0 [--without-progress] destination_vmname FILE [FILE ...]"
	else
		echo "usage: $0 [--without-progress] FILE [FILE ...]"
	fi
	
	echo

	if [ "${0##*/}" = "qvm-move-to-vm" ] || [ "${0##*/}" = "qvm-move" ] ; then
		echo "Move FILE to ~/QubesIncoming/$(hostname)/ in the destination qube."
	else
		echo "Copy FILE to ~/QubesIncoming/$(hostname)/ in the destination qube."
	fi
	
	echo 
	echo "You will be prompted to select the destination qube. If FILE is a directory, it will be copied recursively."	
	exit 1
fi

if [ "$1" = "--without-progress" ] ; then
	export PROGRESS_TYPE=none
	shift
else
	export PROGRESS_TYPE=console
fi


VM="$1"
shift

if [ $PROGRESS_TYPE = console ] ; then
    FILECOPY_TOTAL_SIZE=$(du --apparent-size -c -- "$@" 2> /dev/null | tail -1 | cut -f 1)
    export FILECOPY_TOTAL_SIZE
fi

if [ "$VM" != \$default ]; then
    echo "qvm-copy-to-vm/qvm-move-to-vm tools are deprecated," >&2
    echo "use qvm-copy/qvm-move to avoid typing target qube name twice" >&2
fi

/usr/lib/qubes/qrexec-client-vm "$VM" qubes.Filecopy /usr/lib/qubes/qfile-agent "$@"

if [ "${0##*/}" = "qvm-move-to-vm" ] || [ "${0##*/}" = "qvm-move" ] ; then
	rm -rf -- "$@"
fi
