#!/bin/sh
#
# The Qubes OS Project, http://www.qubes-os.org
#
# Copyright (C) 2010  Rafal Wojtczuk  <rafal@invisiblethingslab.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
#

print_usage() {
cat >&2 <<USAGE
Usage: $0 vmname command arguments
Executes a command in another VM using the qubes.VMShell RPC service.  The
arguments are joined with spaces and passed to "bash -c".

Standard input and output are connected to the command.  Unlike qvm-run in Dom0,
this tool does not propagate standard error or exit codes, nor does it offer
protection against the remote VM messing with your terminal if standard output
is your terminal.

You can use \$dispvm or --dispvm instead of vmname to start a new DisposableVM.
USAGE
}

if [ $# -lt 2 ] ; then
    print_usage
    exit 1
fi

VMNAME="$1"
shift

if [ "$VMNAME" = "--dispvm" ] ; then
    # shellcheck disable=SC2016
    VMNAME='$dispvm'
elif [ "$VMNAME" = "" ] ; then
    print_usage
    exit 1
fi
exec /usr/lib/qubes/qrexec-client-vm "$VMNAME" qubes.VMShell "/usr/lib/qubes/qrun-in-vm" "$@"
