#!/bin/sh
set -e
#
# The Qubes OS Project, http://www.qubes-os.org
#
# Copyright (C) 2010  Rafal Wojtczuk  <rafal@invisiblethingslab.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
#

if [ $# -lt 2 ] ; then
	echo "usage: $0 [--without-progress] dest_vmname file [file]+"
	exit 1
fi

if [ "$1" = "--without-progress" ] ; then
	export PROGRESS_TYPE=none
	shift
else
	export PROGRESS_TYPE=console
fi


VM="$1"
shift

if [ $PROGRESS_TYPE = console ] ; then
    FILECOPY_TOTAL_SIZE=$(du --apparent-size -c -- "$@" 2> /dev/null | tail -1 | cut -f 1)
    export FILECOPY_TOTAL_SIZE
fi

/usr/lib/qubes/qrexec-client-vm "$VM" qubes.Filecopy /usr/lib/qubes/qfile-agent "$@"

if [ "${0##*/}" = "qvm-move-to-vm" ]; then
	rm -rf -- "$@"
fi
