#!/bin/sh
#
# chkconfig: 345 90 90
# description: Executes Qubes core scripts at VM boot
#
# Source function library.
. /etc/rc.d/init.d/functions

start()
{
	echo -n $"Starting Qubes RPC agent:"

	/usr/lib/qubes/qrexec-agent 2>/var/log/qubes/qrexec-agent.log &

	success
	echo ""

	return 0
}

stop()
{
    killproc qrexec-agent
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo $"Usage: $0 {start|stop}"
	exit 3
	;;
esac

exit $RETVAL
