#!/bin/bash
#
# chkconfig: 345 91 91
# description: Executes Qubes core scripts at AppVM boot
#
# This must run after GUI agent has started.  Hence 91.
#
# Source function library.
. /etc/rc.d/init.d/functions

# Source Qubes library.
. /usr/lib/qubes/init/functions

start()
{
	have_qubesdb || return

	if qsvc qubes-dvm; then
		echo -n $"Preparing Qubes DVM:"
		/usr/lib/qubes/init/prepare-dvm.sh && success || failure
		echo
	fi
}

stop()
{
	return 0
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo $"Usage: $0 {start|stop}"
	exit 3
	;;
esac

exit $RETVAL
