#!/bin/bash
#
# chkconfig: 345 90 90
# description: Executes Qubes core scripts at VM boot
#
# Source function library.
# shellcheck disable=SC1091
. /etc/rc.d/init.d/functions

# Source Qubes library.
# shellcheck source=init/functions
. /usr/lib/qubes/init/functions

start()
{
	have_qrexec_agent || return
	echo -n $"Starting Qubes RPC agent:"
	/usr/lib/qubes/qrexec-agent 2>/var/log/qubes/qrexec-agent.log &
	success
	echo ""
	return 0
}

stop()
{
	have_qrexec_agent || return
	killproc qrexec-agent
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo $"Usage: $0 {start|stop}"
	exit 3
	;;
esac

# shellcheck disable=SC2086
exit $RETVAL
