#!/bin/bash
#
# chkconfig: 345 93 93
# description: Starts Qubes Network monitor
#
# Source function library.
. /etc/rc.d/init.d/functions

# Source Qubes library.
. /usr/lib/qubes/init/functions

PIDFILE=/var/run/qubes/qubes-netwatcher.pid

start()
{
    have_qubesdb || return

    if qsvc qubes-netwatcher ; then
        echo -n $"Starting Qubes Network monitor:"
        /sbin/ethtool -K eth0 sg off
        /usr/sbin/qubes-netwatcher &
        success
        echo ""
    fi
}

stop()
{
    if [ -r "$PIDFILE" ]; then
        echo -n "Stopping Qubes Network monitor:"
        kill -9 $(cat $PIDFILE) 2>/dev/null  && success || failure
        echo ""
    fi
	return 0
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo $"Usage: $0 {start|stop}"
	exit 3
	;;
esac

exit $RETVAL
