#!/bin/bash
#
# chkconfig: 345 92 92
# description: Starts Qubes Firewall monitor
#
# Source function library.
# shellcheck disable=SC1091
. /etc/rc.d/init.d/functions

# Source Qubes library.
# shellcheck source=init/functions
. /usr/lib/qubes/init/functions

PIDFILE=/var/run/qubes/qubes-firewall.pid

start()
{
    have_qubesdb || return

    if qsvc qubes-firewall ; then
        echo -n $"Starting Qubes Firewall monitor:"
        /sbin/ethtool -K eth0 sg off
        /usr/sbin/qubes-firewall &
        success
        echo ""
    fi
}

stop()
{
    if [ -r $PIDFILE ]; then
        echo -n "Stopping Qubes Firewall monitor:"
        # shellcheck disable=SC2015
        kill -9 "$(cat "$PIDFILE")" 2>/dev/null && success || failure
        echo ""
    fi
	return 0
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo $"Usage: $0 {start|stop}"
	exit 3
	;;
esac

# shellcheck disable=SC2086
exit $RETVAL
