#!/bin/bash
# Launches a private dbus instance with activatable services as specified in the services folder.
# Copyright (C) 2021 GPLv2 David Hobach <tripleh@hackingthe.net>

set -e -o pipefail

SCRIPT_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
SERVICES="$SCRIPT_DIR/services"

user="$(qubesdb-read "/default-user")"

[[ "$(whoami)" == "root" ]] || { >&2 echo "This script must be run as root." ; exit 1 ; }

printf -v cmd '
mount --bind %q /usr/share/dbus-1/services/
runuser -u %q -- dbus-launch' "$SERVICES" "$user"

unshare -m bash -c "$cmd"
