#!/bin/sh

mkfifo /tmp/qrexec-rpc-stderr.$$
logger -t "$1-$2" -f /tmp/qrexec-rpc-stderr.$$ >/dev/null 2>&1 </dev/null &
exec 2>/tmp/qrexec-rpc-stderr.$$
rm -f /tmp/qrexec-rpc-stderr.$$

QUBES_RPC=/etc/qubes-rpc
LOCAL_QUBES_RPC=/usr/local/etc/qubes-rpc

if ! [ $# = 2 ] ; then
	echo $0: bad argument count, usage: $0 SERVICE-NAME REMOTE-DOMAIN-NAME >&2
	exit 1
fi
export QREXEC_REMOTE_DOMAIN="$2"

for CFG_FILE in $QUBES_RPC/"$1" $LOCAL_QUBES_RPC/"$1"; do
	if [ -s "$CFG_FILE" ]; then
        break
	fi
done

if [ -x "$CFG_FILE" ] ; then
	exec "$CFG_FILE"
	echo "$0: failed to execute handler for" "$1" >&2
	exit 1
else
	exec /bin/sh "$CFG_FILE"
	echo "$0: failed to execute handler for" "$1" >&2
	exit 1
fi
